import { MigrationInterface, QueryRunner } from 'typeorm';

export class AutoGeneratedMigration1755512988862 implements MigrationInterface {
  name = 'AutoGeneratedMigration1755512988862';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "Scores" DROP COLUMN "openDate"`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "Scores" ADD "openDate" varchar(8)`);
  }
}
