version: "3.8"

services:
  score-back:
    image: score-back:1.0.11
    build:
      context: ./score-back
      dockerfile: Dockerfile
      args:
        TARGET_ENV: prod
    container_name: score-back
    ports:
      - "8080:5004"
    networks:
      - score-net
    environment:
      - TZ=Asia/Tehran
      - ENV=prod
    env_file:
      - ./score-back/.env.prod  # Only load production env file

  score-front:
    image: score-front:1.0.11
    build:
      context: ./score-front
      dockerfile: Dockerfile
    container_name: score-front
    ports:
      - "80:3002"
    networks:
      - score-net
    environment:
      - TZ=Asia/Tehran
      - ENV=prod
    env_file:
      - ./score-front/.env.production  # Only load production env file

networks:
  score-net:
    driver: bridge

#docker-compose up --build -d